<a href="https://colab.research.google.com/github/NitinSingh8/self_ML/blob/main/Numpy/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This file contain the all the concept which i know related to numpy.

In [2]:
import numpy as np

In [ ]:
# Create an array
arr = np.array([1,2,3,4])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

In [27]:
# different way to create an array

# you can read the description of function by just hovering on it


arr = np.arange(0,100 ,5)  
print(arr)

print()

arr = np.random.rand(10)   
print(arr)

print()

arr = np.random.randn(10)
print(arr)

print()
arr = np.random.randint(10,100,size=(2,4))
print(arr)

print()

arr = np.linspace(10 , 100, 10)
print(arr)

print()

arr = np.zeros(shape=(2,3))
print(arr)

print()

arr = np.ones((4,4))
print(arr)

print()

arr = np.eye(5)
print(arr)

print()

arr = np.full((2,4),10)
print(arr)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]

[0.98977815 0.28846111 0.28202571 0.42183351 0.50528397 0.83056606
 0.56082332 0.60414662 0.77398608 0.84552729]

[ 0.31236755  1.34186432 -0.37557107 -0.75490797 -0.05361336  0.61370477
 -1.73980063 -0.96436863  0.43324211 -0.94480792]

[[72 44 31 75]
 [52 57 56 75]]

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[10 10 10 10]
 [10 10 10 10]]


In [ ]:
# accessing the data from numpy array

arr = np.random.randint(10,100, size = (3,3))
print(arr)

print()
print(arr[0]) # access 0th row in arr [another way is print(arr[0,:])]

print() 
print(arr[:,0]) # access 0th column

print()
print(arr[2,1]) # access 2nd row and 1th column in arr



In [16]:
# reshape and resize in numpy
'''reshape = change the size and return the changed array but doesn't modify main array
resize = change the size in main array does not return anything '''

arr1 = np.random.randint(10,100,size=(2,4))
print(arr1)

print()
# by reshape
new_arr1 = arr1.reshape(4,2)
print(new_arr1)

print()

# by resize
arr1.resize(4,2) 
print(arr1)

[[68 63 46 24]
 [43 49 28 11]]

[[68 63]
 [46 24]
 [43 49]
 [28 11]]

[[68 63]
 [46 24]
 [43 49]
 [28 11]]


In [30]:
# concatenate two array horizontally( keep in mind that array should have same no. of rows)
arr1 = np.random.randint(10,100,size=(2,4))
print(arr1)

print()

arr2 = np.random.randint(10,100,size=(2,2))
print(arr2)

print()


# using concatenate function
arr3 = np.concatenate((arr1,arr2),axis= 1) # axis = 1 means want to add horizontally
print(arr3)

print()

# using hstack
arr3 = np.hstack((arr1,arr2))
print(arr3)

[[97 32 76 30]
 [22 77 38 62]]

[[17 31]
 [77 93]]

[[97 32 76 30 17 31]
 [22 77 38 62 77 93]]

[[97 32 76 30 17 31]
 [22 77 38 62 77 93]]


In [31]:
# concatenate two array vertically( keep in mind that array should have same no. of columns)
arr1 = np.random.randint(10,100,size=(2,4))
print(arr1)

print()

arr2 = np.random.randint(10,100,size=(4,4))
print(arr2)

print()

# using concatenate function
arr3 = np.concatenate((arr1,arr2),axis= 0) # axis = 0 means want to add vertically
print(arr3)

print()

# using vstack function
arr3 = np.vstack((arr1,arr2))
print(arr3)

[[62 85 70 18]
 [12 49 11 13]]

[[19 56 80 14]
 [28 49 48 82]
 [21 29 86 62]
 [66 50 81 18]]

[[62 85 70 18]
 [12 49 11 13]
 [19 56 80 14]
 [28 49 48 82]
 [21 29 86 62]
 [66 50 81 18]]

[[62 85 70 18]
 [12 49 11 13]
 [19 56 80 14]
 [28 49 48 82]
 [21 29 86 62]
 [66 50 81 18]]


In [40]:
# scalar function in arr
arr = np.random.randint(10,100,size = (4,4))
print(arr)

print()

print(np.max(arr))
print(np.argmax(arr))
print(np.min(arr))
print(np.argmin(arr))

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))


print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.sin(arr))

[[32 19 19 47]
 [56 41 66 23]
 [23 69 74 77]
 [38 41 41 31]]

77
11
19
1
43.5625
41.0
18.96697376362397
[[5.65685425 4.35889894 4.35889894 6.8556546 ]
 [7.48331477 6.40312424 8.1240384  4.79583152]
 [4.79583152 8.30662386 8.60232527 8.77496439]
 [6.164414   6.40312424 6.40312424 5.56776436]]
[[3.4657359  2.94443898 2.94443898 3.8501476 ]
 [4.02535169 3.71357207 4.18965474 3.13549422]
 [3.13549422 4.2341065  4.30406509 4.34380542]
 [3.63758616 3.71357207 3.71357207 3.4339872 ]]
[[7.89629602e+13 1.78482301e+08 1.78482301e+08 2.58131289e+20]
 [2.09165950e+24 6.39843494e+17 4.60718663e+28 9.74480345e+09]
 [9.74480345e+09 9.25378173e+29 1.37338298e+32 2.75851345e+33]
 [3.18559318e+16 6.39843494e+17 6.39843494e+17 2.90488497e+13]]
[[ 0.55142668  0.14987721  0.14987721  0.12357312]
 [-0.521551   -0.15862267 -0.02655115 -0.8462204 ]
 [-0.8462204  -0.11478481 -0.98514626  0.99952016]
 [ 0.29636858 -0.15862267 -0.15862267 -0.40403765]]


In [45]:
# determinant , inverse of matrix
arr = np.random.randint(10,100,size=(4,4))
print(arr)

print()

print(np.linalg.det(arr))

print() 

print(np.linalg.inv(arr))


[[20 21 50 49]
 [79 29 46 75]
 [63 21 56 86]
 [96 80 31 28]]

-608284.9999999971

[[ 0.04863674  0.17084261 -0.16662255 -0.03095917]
 [-0.07370723 -0.22179242  0.21745892  0.05516493]
 [ 0.13480523  0.26084483 -0.2864644  -0.05474572]
 [-0.10541111 -0.24084599  0.26712314  0.04485726]]
